apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: dhruvsha256/go_worker
          envFrom:
            - configMapRef:
                name: worker-configmap
            - secretRef:
                name: worker-secret
